name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node node-version
        run: node-vm
      - uses: Github-Actions-Org-Mateo/Github-Actions@v1
        with:
          node-version: 6
      - name: Log Node Version
        run: node -v

